<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Telemarketing</name>
   <tag></tag>
   <elementGuidId>cff6cc1c-1afb-4999-9ed1-a746fda8566d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_departement-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='job_departement-option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>6d2f69dc-4d36-4639-94d8-290a8da68685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9a1ed13c-420f-4007-88b4-1990cd6d0d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1f04ae41-ea9c-4913-b4b0-2e7aafa1485e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_departement-option-1</value>
      <webElementGuid>00d4320f-21cc-405c-b0f7-a1308fa6c28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b9b2d817-23da-487c-b488-09c7cc758c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f6711ec-0e38-4393-b091-58c6d66dd2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4839bd0-d2d1-418a-b2de-f1729d962049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>42d22303-8e96-493a-a772-8437db5aab70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Telemarketing</value>
      <webElementGuid>c4e5ff83-4fe6-4faf-9627-792ce0945faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_departement-option-1&quot;)</value>
      <webElementGuid>b0b464ff-c540-4521-84ae-2481d64469eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='job_departement-option-1']</value>
      <webElementGuid>a1d5ff31-a3fb-4242-b843-f7a2ebfed304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='job_departement-listbox']/li[2]</value>
      <webElementGuid>21603d21-7e61-440a-9031-0d20dc54cb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terapkan'])[1]/following::li[2]</value>
      <webElementGuid>4ee3181d-60e1-4bcd-ba78-086217574789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[2]</value>
      <webElementGuid>977718e0-8bbb-4c37-bbd5-6422badfa218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'job_departement-option-1' and (text() = ' Telemarketing' or . = ' Telemarketing')]</value>
      <webElementGuid>9974a4e9-86b1-4a38-9590-997b3d4eee34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
